// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SmartCash.EfCore.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SmartCash.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ConsumiveisModelEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SmartCash.EfCore.Models.ConsumiveisModel",
                typeof(ConsumiveisModel),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 2,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var idConsumivel = runtimeEntityType.AddProperty(
                "IdConsumivel",
                typeof(int),
                propertyInfo: typeof(ConsumiveisModel).GetProperty("IdConsumivel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ConsumiveisModel).GetField("<IdConsumivel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var idCategoria = runtimeEntityType.AddProperty(
                "IdCategoria",
                typeof(int),
                propertyInfo: typeof(ConsumiveisModel).GetProperty("IdCategoria", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ConsumiveisModel).GetField("<IdCategoria>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var nome = runtimeEntityType.AddProperty(
                "Nome",
                typeof(string),
                propertyInfo: typeof(ConsumiveisModel).GetProperty("Nome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ConsumiveisModel).GetField("<Nome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);

            var valor = runtimeEntityType.AddProperty(
                "Valor",
                typeof(decimal),
                propertyInfo: typeof(ConsumiveisModel).GetProperty("Valor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ConsumiveisModel).GetField("<Valor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            var key = runtimeEntityType.AddKey(
                new[] { idConsumivel });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { idCategoria });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("IdCategoria") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("IdCategoria") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var categoria = declaringEntityType.AddNavigation("Categoria",
                runtimeForeignKey,
                onDependent: true,
                typeof(CategoriaModel),
                propertyInfo: typeof(ConsumiveisModel).GetProperty("Categoria", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ConsumiveisModel).GetField("<Categoria>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var produtos = principalEntityType.AddNavigation("Produtos",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<ConsumiveisModel>),
                propertyInfo: typeof(CategoriaModel).GetProperty("Produtos", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CategoriaModel).GetField("<Produtos>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Consumivel");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
