// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SmartCash.EfCore.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SmartCash.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ItemModelEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SmartCash.EfCore.Models.ItemModel",
                typeof(ItemModel),
                baseEntityType,
                propertyCount: 6,
                navigationCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 2,
                keyCount: 1);

            var idItem = runtimeEntityType.AddProperty(
                "IdItem",
                typeof(int),
                propertyInfo: typeof(ItemModel).GetProperty("IdItem", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemModel).GetField("<IdItem>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var idConsumivel = runtimeEntityType.AddProperty(
                "IdConsumivel",
                typeof(int),
                propertyInfo: typeof(ItemModel).GetProperty("IdConsumivel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemModel).GetField("<IdConsumivel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var idTransacao = runtimeEntityType.AddProperty(
                "IdTransacao",
                typeof(int),
                propertyInfo: typeof(ItemModel).GetProperty("IdTransacao", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemModel).GetField("<IdTransacao>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var quantidade = runtimeEntityType.AddProperty(
                "Quantidade",
                typeof(decimal),
                propertyInfo: typeof(ItemModel).GetProperty("Quantidade", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemModel).GetField("<Quantidade>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            var valorTotal = runtimeEntityType.AddProperty(
                "ValorTotal",
                typeof(decimal),
                propertyInfo: typeof(ItemModel).GetProperty("ValorTotal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemModel).GetField("<ValorTotal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            var valorUnit = runtimeEntityType.AddProperty(
                "ValorUnit",
                typeof(decimal),
                propertyInfo: typeof(ItemModel).GetProperty("ValorUnit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemModel).GetField("<ValorUnit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            var key = runtimeEntityType.AddKey(
                new[] { idItem });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { idConsumivel });

            var index0 = runtimeEntityType.AddIndex(
                new[] { idTransacao });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("IdConsumivel") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("IdConsumivel") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var produto = declaringEntityType.AddNavigation("Produto",
                runtimeForeignKey,
                onDependent: true,
                typeof(ConsumiveisModel),
                propertyInfo: typeof(ItemModel).GetProperty("Produto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemModel).GetField("<Produto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var itens = principalEntityType.AddNavigation("Itens",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<ItemModel>),
                propertyInfo: typeof(ConsumiveisModel).GetProperty("Itens", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ConsumiveisModel).GetField("<Itens>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("IdTransacao") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("IdTransacao") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var transacao = declaringEntityType.AddNavigation("Transacao",
                runtimeForeignKey,
                onDependent: true,
                typeof(TransacaoModel),
                propertyInfo: typeof(ItemModel).GetProperty("Transacao", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemModel).GetField("<Transacao>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var itens = principalEntityType.AddNavigation("Itens",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<ItemModel>),
                propertyInfo: typeof(TransacaoModel).GetProperty("Itens", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TransacaoModel).GetField("<Itens>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Item");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
