// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using SmartCash.CompiledModels;
using SmartCash.EfCore;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MeuDbContext), typeof(MeuDbContextModel))]
