// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SmartCash.CompiledModels
{
    public partial class MeuDbContextModel
    {
        private MeuDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("aab0447a-689a-4b2e-8871-db1f2289495b"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var categoriaModel = CategoriaModelEntityType.Create(this);
            var consumiveisModel = ConsumiveisModelEntityType.Create(this);
            var itemModel = ItemModelEntityType.Create(this);
            var transacaoModel = TransacaoModelEntityType.Create(this);

            ConsumiveisModelEntityType.CreateForeignKey1(consumiveisModel, categoriaModel);
            ItemModelEntityType.CreateForeignKey1(itemModel, consumiveisModel);
            ItemModelEntityType.CreateForeignKey2(itemModel, transacaoModel);

            CategoriaModelEntityType.CreateAnnotations(categoriaModel);
            ConsumiveisModelEntityType.CreateAnnotations(consumiveisModel);
            ItemModelEntityType.CreateAnnotations(itemModel);
            TransacaoModelEntityType.CreateAnnotations(transacaoModel);

            AddAnnotation("ProductVersion", "9.0.1");
        }
    }
}
