// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCash.EfCore;

#nullable disable

namespace SmartCash.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20260222212839_AlterandoColumnIdProdutoFromConsumiveis")]
    partial class AlterandoColumnIdProdutoFromConsumiveis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("SmartCash.EfCore.Models.CategoriaModel", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconeApresentacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("SmartCash.EfCore.Models.ConsumiveisModel", b =>
                {
                    b.Property<int>("IdConsumivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("IdConsumivel");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Consumivel", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Produto_Valor", "Valor >= 0");
                        });
                });

            modelBuilder.Entity("SmartCash.EfCore.Models.ItemModel", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdConsumivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTransacao")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorUnit")
                        .HasColumnType("TEXT");

                    b.HasKey("IdItem");

                    b.HasIndex("IdConsumivel");

                    b.HasIndex("IdTransacao");

                    b.ToTable("Item", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Item_Quantidade", "Quantidade >= 0");

                            t.HasCheckConstraint("CHK_Item_ValorTotal", "ValorTotal >= 0");

                            t.HasCheckConstraint("CHK_Item_ValorUnit", "ValorUnit >= 0");
                        });
                });

            modelBuilder.Entity("SmartCash.EfCore.Models.TransacaoModel", b =>
                {
                    b.Property<int>("IdTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTransacao");

                    b.ToTable("Transacao", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Transacao_ValorTotal", "ValorTotal >= 0");
                        });
                });

            modelBuilder.Entity("SmartCash.EfCore.Models.ConsumiveisModel", b =>
                {
                    b.HasOne("SmartCash.EfCore.Models.CategoriaModel", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SmartCash.EfCore.Models.ItemModel", b =>
                {
                    b.HasOne("SmartCash.EfCore.Models.ConsumiveisModel", "Produto")
                        .WithMany("Itens")
                        .HasForeignKey("IdConsumivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCash.EfCore.Models.TransacaoModel", "Transacao")
                        .WithMany("Itens")
                        .HasForeignKey("IdTransacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("SmartCash.EfCore.Models.CategoriaModel", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("SmartCash.EfCore.Models.ConsumiveisModel", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SmartCash.EfCore.Models.TransacaoModel", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
